################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
gecko_sdk_4.0.0/hardware/board/src \
gecko_sdk_4.0.0/hardware/generic-interrupt-control \
gecko_sdk_4.0.0/platform/Device/SiliconLabs/EFR32MG21/Source/GCC \
gecko_sdk_4.0.0/platform/Device/SiliconLabs/EFR32MG21/Source \
gecko_sdk_4.0.0/platform/bootloader/api \
gecko_sdk_4.0.0/platform/bootloader/app_properties \
gecko_sdk_4.0.0/platform/common/src \
gecko_sdk_4.0.0/platform/common/toolchain/src \
gecko_sdk_4.0.0/platform/driver/button/src \
gecko_sdk_4.0.0/platform/driver/debug/src \
gecko_sdk_4.0.0/platform/driver/leddrv/src \
gecko_sdk_4.0.0/platform/driver/pwm/src \
gecko_sdk_4.0.0/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.0.0/platform/emdrv/nvm3/src \
gecko_sdk_4.0.0/platform/emlib/src \
gecko_sdk_4.0.0/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154_uc \
gecko_sdk_4.0.0/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.0.0/platform/radio/rail_lib/plugin/rail_util_ant_div \
gecko_sdk_4.0.0/platform/radio/rail_lib/plugin/rail_util_pti \
gecko_sdk_4.0.0/platform/radio/rail_lib/plugin/rail_util_rf_path \
gecko_sdk_4.0.0/platform/service/cli/src \
gecko_sdk_4.0.0/platform/service/device_init/src \
gecko_sdk_4.0.0/platform/service/hfxo_manager/src \
gecko_sdk_4.0.0/platform/service/iostream/src \
gecko_sdk_4.0.0/platform/service/legacy_hal/src \
gecko_sdk_4.0.0/platform/service/legacy_printf/src \
gecko_sdk_4.0.0/platform/service/power_manager/src \
gecko_sdk_4.0.0/platform/service/sleeptimer/src \
gecko_sdk_4.0.0/platform/service/system/src \
gecko_sdk_4.0.0/platform/service/token_manager/src \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/cli \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/common \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/basic \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/counters \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/debug-print \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/end-device-support \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/find-and-bind-initiator \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/groups-client \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/identify \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/interpan \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/network-creator \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/network-creator-security \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/network-steering \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/scan-dispatch \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/scenes-client \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/update-tc-link-key \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zcl_cli \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-commissioning-client \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-commissioning-common \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-commissioning-server \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-scenes-client \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-utility-client \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/plugin/zll-utility-server \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/security \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/service-function \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/signature-decode \
gecko_sdk_4.0.0/protocol/zigbee/app/framework/util \
gecko_sdk_4.0.0/protocol/zigbee/app/util/common \
gecko_sdk_4.0.0/protocol/zigbee/app/util/security \
gecko_sdk_4.0.0/protocol/zigbee/app/util/serial \
gecko_sdk_4.0.0/protocol/zigbee/app/util/zigbee-framework \
gecko_sdk_4.0.0/protocol/zigbee/stack/config \
gecko_sdk_4.0.0/protocol/zigbee/stack/framework \
gecko_sdk_4.0.0/protocol/zigbee/stack/security \
gecko_sdk_4.0.0/protocol/zigbee/stack/zigbee \
gecko_sdk_4.0.0/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.0.0/util/third_party/crypto/mbedtls/library \
gecko_sdk_4.0.0/util/third_party/crypto/sl_component/se_manager/src \
gecko_sdk_4.0.0/util/third_party/crypto/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.0.0/util/third_party/crypto/sl_component/sl_psa_driver/src \
gecko_sdk_4.0.0/util/third_party/printf \
gecko_sdk_4.0.0/util/third_party/printf/src \

